name: hotel

services:
  web:
    build:
      context: .
    container_name: web
    command: >
      sh -c "poetry run python manage.py migrate --no-input &&
             poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=4"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod

  db:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hotel_db
      - TZ=Asia/Yekaterinburg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/var/www/hotel/static:ro

