# Generated by Django 5.1.7 on 2025-04-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotelroom_id_roombooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='room',
            new_name='room_id',
        ),
    ]
