# Generated by Django 5.1.7 on 2025-04-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_room_roombooking_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='room_id',
            new_name='room',
        ),
    ]
