# Generated by Django 5.1.7 on 2025-04-02 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_room_id_roombooking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.hotelroom'),
        ),
        migrations.RenameField(
            model_name='roombooking',
            old_name='room',
            new_name='room_id',
        ),
    ]
