# Generated by Django 5.1.7 on 2025-04-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_roombooking_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='room_number',
            field=models.IntegerField(default=10, unique=True),
            preserve_default=False,
        ),
    ]
