# Generated by Django 5.1.7 on 2025-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotelroom_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
