# Generated by Django 5.1.7 on 2025-04-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotelroom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='room_number',
        ),
    ]
