# Generated by Django 5.1.7 on 2025-04-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_hotelroom_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='room_number',
            field=models.IntegerField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
