# Generated by Django 5.1.7 on 2025-04-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_hotelroom_room_number_alter_hotelroom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='id',
            new_name='booking_id',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='room_number',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='room_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
