# Generated by Django 5.1.7 on 2025-04-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_rename_id_roombooking_booking_id_remove_hotelroom_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomBooking',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='HotelRoom',
            new_name='Room',
        ),
    ]
