# Generated by Django 5.1.7 on 2025-04-12 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_rename_roombooking_booking_rename_hotelroom_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(db_column='hotel_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
